"""add wishlists

Revision ID: f399ed2f1fd2
Revises: 8efdbcc5aa1e
Create Date: 2026-10-08 16:52:18.064910
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f399ed2f1fd2"
down_revision: str | None = "8efdbcc5aa1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlists",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_wishlists_product_id_products"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_wishlists_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "product_id", name=op.f("pk_wishlists")),
    )
    op.create_index(op.f("ix_wishlists_product_id"), "wishlists", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlists_product_id"), table_name="wishlists")
    op.drop_table("wishlists")
    # ### end Alembic commands ###
