"""add fandom samples

Revision ID: 262cecdddbbd
Revises: d0bcc9df44ea
Create Date: 2026-10-08 17:14:24.353859
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "262cecdddbbd"
down_revision: str | None = "d0bcc9df44ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fandom_samples",
        sa.Column("region_code", sa.String(length=12), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.CheckConstraint("count >= 0", name=op.f("ck_fandom_samples_count")),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["interests.id"], name=op.f("fk_fandom_samples_interest_id_interests"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["region_code"], ["regions.code"], name=op.f("fk_fandom_samples_region_code_regions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("region_code", "interest_id", name=op.f("pk_fandom_samples")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fandom_samples")
    # ### end Alembic commands ###
