"""add trade posts

Revision ID: 8a53eae82fac
Revises: 262cecdddbbd
Create Date: 2026-10-08 17:16:58.252941
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8a53eae82fac"
down_revision: str | None = "262cecdddbbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("region_code", sa.String(length=12), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("interest_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.String(length=60), nullable=False),
        sa.Column("condition", sa.String(length=10), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("trade_method", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("condition IN ('new', 'like_new', 'used')", name=op.f("ck_trade_posts_condition")),
        sa.CheckConstraint("kind IN ('have', 'want', 'sell')", name=op.f("ck_trade_posts_kind")),
        sa.CheckConstraint("status IN ('open', 'done', 'hidden')", name=op.f("ck_trade_posts_status")),
        sa.CheckConstraint("trade_method IN ('direct', 'delivery', 'both')", name=op.f("ck_trade_posts_trade_method")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_trade_posts_price")),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["interests.id"], name=op.f("fk_trade_posts_interest_id_interests"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_trade_posts_product_id_products"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["region_code"], ["regions.code"], name=op.f("fk_trade_posts_region_code_regions")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trade_posts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_posts")),
    )
    op.create_index(op.f("ix_trade_posts_interest_id"), "trade_posts", ["interest_id"], unique=False)
    op.create_index(op.f("ix_trade_posts_product_id"), "trade_posts", ["product_id"], unique=False)
    op.create_index(op.f("ix_trade_posts_region_code"), "trade_posts", ["region_code"], unique=False)
    op.create_index(op.f("ix_trade_posts_user_id"), "trade_posts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_posts_user_id"), table_name="trade_posts")
    op.drop_index(op.f("ix_trade_posts_region_code"), table_name="trade_posts")
    op.drop_index(op.f("ix_trade_posts_product_id"), table_name="trade_posts")
    op.drop_index(op.f("ix_trade_posts_interest_id"), table_name="trade_posts")
    op.drop_table("trade_posts")
    # ### end Alembic commands ###
