"""add cancel requests

Revision ID: 835590172129
Revises: 8efdbcc5aa1e
Create Date: 2026-10-08 17:18:42.217695
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "835590172129"
down_revision: str | None = "8efdbcc5aa1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cancel_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_cancel_requests_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cancel_requests")),
    )
    op.create_index(op.f("ix_cancel_requests_order_id"), "cancel_requests", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cancel_requests_order_id"), table_name="cancel_requests")
    op.drop_table("cancel_requests")
    # ### end Alembic commands ###
