"""add pixel local regions interests

Revision ID: d0bcc9df44ea
Revises: f399ed2f1fd2
Create Date: 2026-10-08 17:12:26.172023
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d0bcc9df44ea"
down_revision: str | None = "f399ed2f1fd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("type IN ('work', 'character', 'style', 'product_type')", name=op.f("ck_interests_type")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["interests.id"], name=op.f("fk_interests_parent_id_interests"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interests")),
    )
    op.create_index(op.f("ix_interests_type"), "interests", ["type"], unique=False)
    op.create_table(
        "regions",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("parent_code", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.CheckConstraint("level IN ('sido', 'sigungu', 'zone')", name=op.f("ck_regions_level")),
        sa.ForeignKeyConstraint(["parent_code"], ["regions.code"], name=op.f("fk_regions_parent_code_regions")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_regions")),
    )
    op.create_index(op.f("ix_regions_parent_code"), "regions", ["parent_code"], unique=False)
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["interests.id"], name=op.f("fk_user_interests_interest_id_interests"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_interests_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "interest_id", name=op.f("pk_user_interests")),
    )
    op.create_index(op.f("ix_user_interests_interest_id"), "user_interests", ["interest_id"], unique=False)
    op.add_column("users", sa.Column("region_code", sa.String(length=12), nullable=True))
    op.add_column("users", sa.Column("fandom_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("users", sa.Column("profile_public", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.create_index(op.f("ix_users_region_code"), "users", ["region_code"], unique=False)
    op.create_foreign_key(op.f("fk_users_region_code_regions"), "users", "regions", ["region_code"], ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_region_code_regions"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_region_code"), table_name="users")
    op.drop_column("users", "profile_public")
    op.drop_column("users", "fandom_opt_in")
    op.drop_column("users", "region_code")
    op.drop_index(op.f("ix_user_interests_interest_id"), table_name="user_interests")
    op.drop_table("user_interests")
    op.drop_index(op.f("ix_regions_parent_code"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_interests_type"), table_name="interests")
    op.drop_table("interests")
    # ### end Alembic commands ###
