"""add faqs

Revision ID: 83ddc494104f
Revises: 0001_init
Create Date: 2026-10-08 16:19:38.176246
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '83ddc494104f'
down_revision: str | None = '0001_init'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
